const allTagalogHealthKeywords = [
    "Aneurysm ng aorta sa tiyan",
    "Akut na cholecystitis",
    "Akut na lymphoblastic leukemia",
    "Akut na myeloid leukemia",
    "Akut na pancreatitis",
    "Maling paggamit ng alak",
    "Pagkalason sa alak",
    "Sakit sa atay na may kaugnayan sa alak",
    "Sakit na Alzheimer",
    "Kanser sa anal",
    "Anaphylaxis",
    "Angioedema",
    "Ankylosing",
    "Ankylosing spondylitis",
    "Pagkabalisa",
    "Mga sakit sa pagkabalisa sa mga bata",
    "Asbestosis",
    "Hika",
    "Sakit sa kakulangan ng atensyon at hyperactivity",
    "Bakterya",
    "Bakteryal",
    "Bacterial vaginosis",
    "Benigno",
    "Benign na paglawak ng prostate",
    "Kanser sa bile duct",
    "Labis na pagkain",
    "Pantog",
    "Kanser sa pantog",
    "Dugo",
    "Kanser sa dugo",
    "Pagkalason sa dugo",
    "Buto",
    "Kanser sa buto",
    "Bituka",
    "Kanser sa bituka",
    "Pagkawala ng kontrol sa bituka",
    "Polyp sa bituka",
    "Utak",
    "Tumor sa utak",
    "Suso",
    "Kanser sa suso",
    "Bunyon",
    "lagnat",
];

export default allTagalogHealthKeywords;