const allTagalogHealthKeywords = [
    "Akut na cholecystitis",
    "Akut na lymphoblastic leukemia",
    "Akut na myeloid leukemia",
    "Akut na pancreatitis",
    "Aneurysm ng aorta sa tiyan",
    "Aneurysm ng aorta",
    "Anaphylaxis",
    "Angioedema",
    "Ankylosing",
    "Ankylosing spondylitis",
    "Asbestosis",
    "Atay",
    "Alak",
    "Altapresyon",
    "Baga",
    "Bacterial vaginosis",
    "Balanseng Diyeta",
    "Bakterya",
    "Bato",
    "Benigno",
    "Buto",
    "Bakuna",
    "Bali",
    "Bituka",
    "Bunyon",
    "Cancer sa dugo",
    "Diyabetes",
    "Dugo",
    "Eksaminasyon",
    "Ehersisyo",
    "Hika",
    "Hirap sa Paghinga",
    "Istroke",
    "Kagat ng insekto",
    "Kalusugan",
    "Kalusugan Pangkaisipan",
    "Kirot",
    "Kanser",
    "Kagalingan",
    "Kanser sa bile duct",
    "Kanser sa dugo",
    "Kanser sa anal",
    "Kanser sa buto",
    "Kanser sa bituka",
    "Kanser sa suso",
    "Labis na pagkain",
    "Labis na katabaan",
    "lagnat",
    "Lunas",
    "Matamlay",
    "Makating Lalamunan",
    "Mga kondisyong maternal",
    "Mga bukol sa katawan",
    "Malabong paningin",
    "Mahapdi na Balat",
    "Makati ng Balat",
    "Medisina",
    "Namamalat ng Boses",
    "Nanunuklap na Balat",
    "Pamamaga ng mga mata",
    "Pagkahilo",
    "Pagkabalisa",
    "Pamamaga",
    "Pantal",
    "Pagduduwal",
    "Pagtatae",
    "Pangunahing Lunas",
    "Pangangasim ng Sikmura",
    "Pagbunot ng ngipin",
    "Paghilab ng Tiyan",
    "Pag-abuso sa droga at alkohol",
    "Pagkalason",
    "Pulso",
    "Pulmonya",
    "Puso",
    "Polyp sa bituka",
    "Pantog",
    "Utak",
    "Suso",
    "Sipon",
    "Pag-abuso sa droga at alkohol",
    "Trangkaso",
    "Tuberkulosis",
    "Tumor sa utak",
    "Tibok ng puso",
    "Tigdas",
    "Ubo"
];

export default allTagalogHealthKeywords;