const extraWords: string[] = [
"AIDS",
"Acquired Immunodeficiency Syndrome",
"Acute Bronchitis",
"Adiposity",
"Aging",
"Allergic Diseases",
"Allergic Reactions",
"Alzheimer Disease",
"Anaphylactic Shock",
"Anaphylaxis",
"Antineoplastic Agents",
"Antineoplastic Therapy",
"Anxiety",
"Anxiety Disorder",
"Anxiety Disorders",
"Arthritis",
"Arthritis, Rheumatoid",
"Asbestos-Related Diseases",
"Asbestosis",
"Asthma",
"Autoimmune Diseases",
"Bacteria",
"Bacterial Infections",
"Bacterial Meningitis",
"Bacterium",
"Biological Aging",
"Blood",
"Borreliosis",
"Brain Attack",
"Bronchial Asthma",
"Bronchial Hyperreactivity",
"Bronchitis",
"Bronchitis, Acute",
"Bronchitis, Chronic",
"Bulimia",
"Bulimia Nervosa",
"Bursa Inflammation",
"Bursa, Inflammation",
"Bursitis",
"Cancer",
"Cancer Chemotherapy",
"Cancer Treatment",
"Carcinoma",
"Cardiovascular Diseases",
"Cardiovascular System",
"Cerebrovascular Accident",
"Chemotherapy, Adjuvant",
"Chickenpox",
"Chronic Bronchitis",
"Chronic Disease",
"Chronic Diseases",
"Chronic Polyarthritis",
"Connective Tissue Diseases",
"Cutaneous Melanoma",
"Dementia",
"Dementia, Multi-Infarct",
"Dementia, Presenile",
"Dementia, Primary",
"Dementia, Vascular",
"Dementias",
"Demographic Factors",
"Dermatophytosis",
"Diabetes Insipidus",
"Diabetes Mellitus",
"Diabetes Mellitus, Insulin-Dependent",
"Diabetes Mellitus, Non-Insulin-Dependent",
"Diabetes, Insulin-Dependent",
"Diabetes, Non-Insulin-Dependent",
"Diarrhea",
"Diarrhea, Acute",
"Diarrhea, Chronic",
"Diarrhea, Infantile",
"Diarrhoea",
"Disease Classification",
"Dizziness",
"Ear Diseases",
"Eating Disorders",
"Endocrine Disorders",
"Environmental Diseases",
"Epidemic Parotitis",
"Excessive Body Fat",
"Frontotemporal Dementia",
"Fungal Diseases",
"Gastrointestinal Disorders",
"Generalized Anxiety Disorder",
"Giddiness",
"Gout",
"Gouty Arthritis",
"HIV Infections",
"HIV/AIDS",
"Heat Exhaustion",
"Heat Stroke",
"Hematologic Diseases",
"Hemolymph",
"Hemorrhage",
"Hepatitis",
"Hepatitis A",
"Hepatitis B",
"Hepatitis C",
"High Blood Pressure",
"Hodgkin Disease",
"Hodgkin's Disease",
"Hodgkin's Lymphoma",
"Hypersensitivity",
"Hypertension",
"Hyperthermia",
"Hyperuricemia",
"Immune System Diseases",
"Immunologic Deficiency Syndromes",
"Infantile Paralysis",
"Infectious Disease Treatment",
"Infectious Diseases",
"Inflammatory Diseases",
"Insomnia",
"Joint Inflammation",
"Leukemia",
"Leukemia, Acute",
"Leukemia, Chronic",
"Leukemia, Lymphocytic",
"Leukemia, Myeloid",
"Lewy Body Disease",
"Liver Diseases",
"Liver Inflammation",
"Long-term",
"Long-term Care",
"Lung Diseases",
"Lung Inflammation",
"Lupus Erythematosus, Systemic",
"Lyme Borreliosis",
"Lyme Disease",
"Lymphatic Diseases",
"Lymphoma, Hodgkin",
"Malaria",
"Malaria Parasite",
"Malignant Melanoma",
"Malignant Mesothelioma",
"Malignant Neoplasm",
"Malignant Sarcoma",
"Malnutrition",
"Measles",
"Medical Terminology",
"Melanoma",
"Melanoma, Cutaneous Malignant",
"Meningitis",
"Meningitis, Bacterial",
"Meningitis, Viral",
"Meningococcal Meningitis",
"Mental Disorders",
"Mesothelioma",
"Metabolic Diseases",
"Metabolic Disorders",
"Microbiology",
"Movement Disorders",
"Mumps",
"Musculoskeletal Diseases",
"Mycobacterium Infections",
"Mycobacterium tuberculosis Infection",
"Neoplasms",
"Neoplastic Diseases",
"Neurodegenerative Diseases",
"Neurologic Disorders",
"Neurological Disorders",
"Neurotic Disorders",
"Nutritional Deficiency",
"Nutritional and Metabolic Diseases",
"Obesity",
"Occupational Diseases",
"Oncological Diseases",
"Osteoarthritis",
"Overweight",
"Paralysis Agitans",
"Parasitic Diseases",
"Parkinson Disease",
"Parkinsonian Disorders",
"Parotitis, Epidemic",
"Persistent",
"Physiological Processes",
"Plasmodia",
"Plasmodium",
"Plasmodium Infection",
"Plasmodium Infections",
"Plasmodium Species",
"Pneumonia",
"Polio",
"Poliomyelitis",
"Poliovirus Infections",
"Protozoan Infections",
"Psychiatric Disorders",
"Public Health",
"Pulmonary Asbestosis",
"Pulmonary Fibrosis",
"Pulmonary Infection",
"RA",
"Respiratory Tract Diseases",
"Rheumatic Diseases",
"Rheumatoid Arthritis",
"Ringing in the Ears",
"Rubeola",
"SLE",
"Sarcoma",
"Sarcoptes scabiei",
"Sarcoptic Mange",
"Scabies",
"Senescence",
"Senile Dementia",
"Severe Allergic Reaction",
"Shaking Palsy",
"Skin Diseases",
"Skin Neoplasms",
"Sleep Disorders",
"Sleep Initiation and Maintenance Disorders",
"Sleeplessness",
"Soft Tissue Neoplasms",
"Soft Tissue Sarcoma",
"Stroke",
"Systemic Lupus Erythematosus",
"TB",
"Temperature Regulation Disorders",
"The Runs",
"The Trots",
"Tinea",
"Tinnitus",
"Tuberculosis",
"Undernutrition",
"VZV Infection",
"Varicella",
"Varicella-Zoster Virus Infection",
"Vector-Borne Diseases",
"Vertigo",
"Viral Diseases",
"Viral Hepatitis",
"Viral Meningitis"
];

export default extraWords;
