const termsArray: string[] = [
"AD",
"AIDS",
"AIDS Related Infections",
"Abdominal Pain",
"Acne",
"Acne Vulgaris",
"Acne vulgaris",
"Acquired Bronchiectasis",
"Acute Bronchitis",
"Acute Diarrhea",
"Acute Flaccid Paralysis",
"Acute Gastroenteritis",
"Acute Gastroenteritis with Diarrhea",
"Acute Hepatitis E",
"Acute Inflammatory Conditions",
"Acute Insomnia",
"Acute Medical Conditions",
"Acute Necrotizing Pancreatitis",
"Acute Pancreatitis",
"Acute Pancreatitis AP",
"Acute Pleurisy",
"Acute and Chronic Bronchitis",
"Acute sinusitis",
"Adjustment Disorders",
"Adult onset Intolerances",
"Age Related Diseases",
"Aging",
"Aging Related Dementia",
"Aging Related Diseases",
"Airway Inflammation",
"Airway Obstruction",
"Alcohol Induced Pancreatitis",
"Allergic Conjunctivitides",
"Allergic Disorders",
"Allergic conjunctivitis",
"Alzheimer",
"Alzheimer Disease",
"Alzheimer's",
"Alzheimer's Disease",
"Alzheimer's Syndrome",
"Alzheimer's Type Dementia",
"Aneurysm",
"Aneurysm tinnitus",
"Anxiety",
"Anxiety Disorders",
"Apoplexy",
"Appendicitis",
"Appendicitis Perforated",
"Appendicitis Ruptured",
"Ascended Bacteria",
"Aspiration Pneumonia",
"Asthma",
"Atopic Conjunctivitides",
"Auditory Conditions",
"Auditory Impairments",
"Aura",
"Aura Disorders",
"Autoimmune Disease",
"Autoimmune Neurological Disorders",
"Autoimmune Pancreatitis",
"Baby Bottle Tooth Decay",
"Baby bottle tooth decay",
"Back Pain",
"Bacterial Gastroenteritis",
"Bacterial Infection",
"Bacterial Infections",
"Bacterial Meningitis",
"Balance Disorders",
"Behavioral Disorders",
"Behavioral Sleep Disorders",
"Benign Paroxysmal Positional Vertigo BPPV",
"Biduoterian fever",
"Biliary Calculi",
"Biliary Calculi Common Bile Duct",
"Biliary Pancreatitis",
"Biliary calculus",
"Biliary colic",
"Bilious Headache",
"Binge Eating Disorder",
"Binge Eating Disorder with Purging",
"Binge Eating and Purging Disorder",
"Blackwater fever",
"Bladder Disorders",
"Bladder Infection",
"Bladder Pain",
"Bladder and Urinary Tract Infection",
"Blood Heart and Circulation",
"Bottle Feeding Decay",
"Bottle Mouth Syndrome",
"Bottle carries",
"Bottle mouth",
"Bowel Obstruction",
"BPPV",
"Bradykinesia",
"Brain Disorders",
"Brain Fever",
"Bronchial Asthma",
"Bronchial Conditions",
"Bronchial Cough",
"Bronchial Cyst Formation",
"Bronchial Dilation",
"Bronchial Disorders",
"Bronchial Hyperreactivity",
"Bronchiectasis",
"Bronchitis",
"Bulimia",
"Bulimia Nervosa",
"Burning Urine",
"Caffeine Headache",
"Calcium oxalate stones",
"Calculi Biliary",
"Calculi Kidney",
"Calculi Renal",
"Calculus Kidney",
"Calculus Renal",
"Cardiac Arrest",
"Cardiac Decompensation",
"Cardiac Insufficiency",
"Cardiac Problems",
"Cardiovascular Diseases",
"Central Nervous System CNS Diseases",
"Central Nervous System CNS Infections",
"Cephalalgia",
"Cerebral Disorders",
"Cerebrovascular",
"Cerebrovascular Accident",
"Cerebrovascular Disease",
"Cerebrovascular Diseases",
"Cerebrovascular Disorders",
"Chemical conjunctivitis",
"Chest Pain",
"Chest Pain Syndromes",
"CHF",
"Childhood Digestive Disorders",
"Childhood Diseases",
"Childhood Infectious Diseases",
"Cholelithiasis",
"Chronic Bronchitis",
"Chronic Conditions",
"Chronic Constipation",
"Chronic Cough",
"Chronic Diarrhea",
"Chronic Infectious Diseases",
"Chronic Inflammatory Conditions",
"Chronic Insomnia",
"Chronic Migraine",
"Chronic Obstructive Pulmonary Disease COPD",
"Chronic Pain Conditions",
"Chronic Pain Syndromes",
"Chronic Pancreatitis",
"Chronic Pancreatitis CP",
"Chronic Pleurisy",
"Chronic Respiratory Conditions",
"Chronic Respiratory Diseases",
"Chronic Venous Insufficiency",
"Circadian Rhythm Disorders",
"Classic Migraine",
"Clicking Tinnitus",
"Cluster Headache",
"Cluster Headaches",
"Cognitive Decline",
"Cognitive Decline in the Elderly",
"Cognitive Disorders",
"Cold sore",
"Colitis Ulcerative",
"Colitis Ulcerative Chronic",
"Colitis Ulcerative Fulminant",
"Colon Disorders",
"Colonic Diseases",
"Common Bile Duct Calculi",
"Common Bile Duct Gall Stone",
"Common Bile Duct Gall Stones",
"Common Bile Duct Gallstone",
"Common Bile Duct Gallstones",
"Common Migraine",
"Community Acquired Pneumonia CAP",
"Conductive hearing loss",
"Congenital Bronchiectasis",
"Congestive Heart Failure",
"Congestive Heart Failure CHF",
"Congestive Heart Failure Syndromes",
"Conjuctivitis",
"Conjunctivitides Allergic",
"Conjunctivitis Atopic",
"Constipation",
"Consumption",
"Contagious Skin Disorders",
"Coronary Artery Diseases",
"Cough",
"Cough Disorders",
"COPD",
"Cranial Neuralgias",
"Cranial Pain",
"Craniofacial Disorders",
"Craniofacial Pain",
"Croup",
"Croupy Cough",
"Cyclamate",
"Cystic Bronchiectasis",
"Cystic acne",
"Cystine stones",
"Cystitis",
"Cystitis and Irritable Bladder",
"DAT",
"Deafness",
"Deafness Categories",
"Deafness Transitory",
"Deafnesses Transitory",
"Decreased hearing",
"Dementia",
"Dementia of the Alzheimer Type DAT",
"Dementia of the Elderly",
"Dementias",
"Demyelinating Diseases",
"Dental Caries",
"Dental caries",
"Dermatologic Conditions",
"Dermatological Conditions",
"Developmental Disorders",
"Diarrhea",
"Diarrhea Acute",
"Diarrhea Chronic",
"Diarrhea Infectious",
"Diarrhea Travelers",
"Diarrhea Watery",
"Diarrheas",
"Diastolic Heart Failure",
"Dietary Disorders",
"Digestive Disorders",
"Digestive Health Conditions",
"Digestive System",
"Disabling Conditions",
"Dizziness",
"Dry Pleurisy",
"ECC",
"ENT",
"ENT Conditions",
"ENT Disorders",
"ERCP",
"Ear Disorders",
"Ear Nose and Throat",
"Ear buzzing",
"Ear infection tinnitus",
"Early Childhood Caries",
"Early Onset Alzheimer's Disease",
"Early childhood caries ECC",
"Eating Disorder Bulimia",
"Eating Disorders",
"Elevated Body Temperature",
"Elevated temperature",
"Emotional Disorders",
"Emotional Distress",
"Endoscopic retrograde cholangiopancreatography ERCP gallstones",
"Enlarged bladder",
"Enterovirus Infections",
"Enzyme Deficiencies",
"Epilepsy",
"Epileptic Seizures",
"Epileptic Syndromes",
"Epityphlitis",
"Equilibrium Disturbances",
"Eradicated Diseases Region Specific",
"Exertion Headache",
"Extrapulmonary Tuberculosis",
"Extrapyramidal Disorders",
"Facial Pain",
"Facial Pain Disorders",
"Faintness",
"Falciparum malaria",
"Familial Alzheimer's Disease",
"Familial Disorders",
"Febrile",
"Febrile Disorders",
"Febrile Response",
"Fever",
"Fever Marsh",
"Fever Remittent",
"Feverish Condition",
"Filiform warts",
"Food Intolerances",
"Fulminant Ulcerative Colitis",
"Functional Constipation",
"Fungal Meningitis",
"Gall Stone",
"Gall Stones",
"Gall Stones Common Bile Duct",
"Gallbladder attack",
"Gallstone",
"Gallstone attack",
"Gallstones",
"Gallstones Common Bile Duct",
"Gastroenteritis",
"Gastroenteritis in Children",
"Gastrointestinal Diseases",
"Gastrointestinal Disorders",
"Gastrointestinal Infections",
"Genetic Epilepsies",
"Genetic Respiratory Diseases",
"Gerontological Dementia",
"Glomerulonephritides Lupus",
"Glomerulonephritis Lupus",
"Guttate psoriasis",
"HAP",
"HEV",
"HEV infection",
"Hangover Headache",
"Headache",
"Headache Disorders",
"Headaches",
"Hearing Deficiencies",
"Hearing Disorders",
"Hearing Disorders Spectrum",
"Hearing Impairment",
"Hearing Loss Classifications",
"Hearing Loss Transitory",
"Hearing Loss Types",
"Hearing Loss Variants",
"Hearing loss",
"Heart Attack",
"Heart Diseases",
"Heart Failure",
"Heart Problems",
"Heart Transplantation",
"Hemorrhagic Stroke",
"Hepatitis E",
"Hereditary Pancreatitis",
"Hoarseness",
"Hospital Acquired Pneumonia HAP",
"Human scabies",
"Hunger Headache",
"Hypertensive Heart Diseases",
"Hyperthermia",
"Hypoacuses",
"Hypoacusis",
"Hypolactasia",
"Idiopathic Pancreatitis",
"Ileus",
"Immune System",
"Induced Tinnitus Noise",
"Infantile paralysis",
"Infection Plasmodium",
"Infection Sinus",
"Infections",
"Infections Plasmodium",
"Infections Sinus",
"Infections and Fevers",
"Infectious Diarrhea",
"Infectious Diseases",
"Infectious Diseases in Children",
"Infectious Gastroenteritis",
"Infectious Lung Diseases",
"Infectious Respiratory Diseases",
"Infestations and Parasitic Diseases",
"Inflamed Throat",
"Inflammation conjunctiva",
"Inflammatory Airway Diseases",
"Inflammatory Bowel Disease",
"Inflammatory Conditions of the Larynx",
"Inflammatory Diseases",
"Insomnia",
"Intestinal Disorders",
"Irritable Bladder",
"Ischemic Stroke",
"Kidney Calculus",
"Kidney Stone",
"Kidney Stones",
"Kidneys and Urinary System",
"Labyrinthine Vertigo",
"Lactase",
"Lactase Non Persistence",
"Lactase Persistence",
"Lactase Phlorizin Hydrolase",
"Lactose Intolerance",
"Lactose Intolerance Adult Type",
"Lactose Malabsorption",
"Lactose intolerance",
"Laryngeal Diseases",
"Laryngitis",
"Laryngotracheobronchitis",
"Late Onset Dementia",
"Leudet Tinnitus",
"Leudet's Tinnitus",
"Lightheadedness",
"Liver",
"Loss Hearing",
"Loss Transitory Hearing",
"Loss of hearing",
"Lung Cancer Cough",
"Lung Fever",
"Lung Infection",
"Lung Inflamation",
"Lung and Respiratory Disorders",
"Lungs and Breathing",
"Lupus",
"Lupus Glomerulonephritides",
"Lupus Glomerulonephritis",
"Lupus Nephritides",
"Lupus glomerular disease",
"Malaria",
"Marsh Fever",
"Memory Disorders",
"Meniere disease tinnitus",
"Meningitis",
"Menstrual Headache",
"Menstrual Migraine",
"Mental Health Conditions",
"Mental Health Disorders",
"Metabolic Syndromes",
"Migraine",
"Migraine Headache",
"Migraine with Aura",
"Migraine without Aura",
"Miliary Tuberculosis",
"Mood Disorders",
"Motor Neuron Diseases",
"Movement Disorders",
"Multiple Sclerosis",
"Multiple Sclerosis MS",
"Muscle Rigidity",
"Mycobacterial Diseases",
"Mycobacterial Infection",
"Mycobacterium Tuberculosis",
"Myelinoclastic Diseases",
"Myocardial Infarction",
"Necrotizing Pancreatitis",
"Nephritides Lupus",
"Nephritis Lupus",
"Nephritis lupus",
"Nephrolith",
"Nephrolithiasis",
"Nervous Headaches",
"Nervousness",
"Neurodegenerative Diseases",
"Neurological Disorders",
"Neuropathic Pain",
"Neuropathic Pain Disorders",
"Neurotic Disorders",
"Nocturnal Asthma",
"Noise Induced Tinnitus",
"Noises or buzzing in the ears",
"Non Infectious Gastroenteritis",
"Non infectious Diarrhea",
"Nursing Bottle Caries",
"Nursing Bottle Decay",
"Nursing bottle caries",
"Nutritional Deficiencies",
"Objective Tinnitus",
"Obstipation",
"Obstructive Bronchiectasis",
"Obstructive Lung Diseases",
"Ocular condition",
"Older Adults",
"Otitis media tinnitus",
"Pain Disorders",
"Pain Syndromes",
"Painful Tic",
"Painful Urination",
"Palmoplantaris Pustulosis",
"Paludism",
"Pancreatitis",
"Panic",
"Paralysis",
"Paralysis Agitans",
"Paralytic Diseases",
"Parasitic Skin Infections",
"Parkinson Disease",
"Parkinson's",
"Parkinson's Disease",
"Parkinsonianism",
"Pelvic Pain",
"Pelvic Pain Disorders",
"Perforated Appendicitis",
"Periungual warts",
"Pharyngitis",
"Phlebography",
"Phtisis",
"Pimples",
"Pink eye",
"Pinkeye",
"Plane juvenile warts",
"Plantar warts",
"Plaque psoriasis",
"Plasmodium",
"Plasmodium Infection",
"Plasmodium Infections",
"Pleural Disorders",
"Pleural Effusion",
"Pleural Inflammation",
"Pleurisy",
"Pleuritis",
"Pneumonia",
"Polio",
"Poliomyelitis",
"Poliovirus",
"Positional Vertigo",
"Potential Heart Problems",
"Presbycusis",
"Primary Headaches",
"Primary Insomnia",
"Progressive Disorders",
"Progressive MS",
"Prolonged Bottle Use Decay",
"Psoriases",
"Psoriasis",
"Psoriasis vulgaris",
"Psychiatric Disorders",
"Psychological Disorders",
"Psychophysiological Disorders",
"Pulmonary Diseases",
"Pulmonary Tuberculosis",
"Pulsatile Tinnitus",
"Pustular Psoriasis of Palms and Soles",
"Pustular psoriasis",
"Pustulosis Palmaris et Plantaris",
"Pustulosis of Palms and Soles",
"Pyrexia",
"Pyrexias",
"Quartan malaria",
"Reactive Airway Disease",
"Rebound Headache",
"Recurrent Headaches",
"Relapsing Remitting MS",
"Remittent Fever",
"Renal Calculi",
"Renal Calculus",
"Renal calculi",
"Respiratory Diseases",
"Respiratory Hypersensitivity",
"Respiratory Illnesses",
"Respiratory Tract Infections",
"Rhinosinusitis",
"Ringing Buzzing Tinnitus",
"Ringing in the ears",
"Ruptured Appendicitis",
"Saphenous Vein",
"Sarcoptes scabiei",
"Scabies",
"Sclerosis Disseminata",
"Scratchy Throat",
"Secondary Headache",
"Secondary Insomnia",
"Secondary Pleurisy",
"Seizure",
"Seizure Disorders",
"Seizures",
"Senile Degeneration",
"Senile Dementia",
"Senility",
"Sensorineural Disorders",
"Sensorineural hearing loss",
"Shaking Palsy",
"Sinus Cough",
"Sinus Headache",
"Sinus Infection",
"Sinus Infections",
"Sinus infection",
"Sinusitides",
"Sinusitis",
"Sinusitis acute",
"Sinusitis chronic",
"Skin",
"Skin Hair and Nails",
"Sleep Apnea",
"Sleep Deprivation",
"Sleep Disorders",
"Sleep Disorders Intrinsic",
"Sleep Disorders Psychological",
"Sleep Hygiene",
"Sleep Initiation and Maintenance Disorders",
"Sleep Maintenance Insomnia",
"Sleep Onset Insomnia",
"Sleeping Problems",
"Sleeplessness",
"Slow Transit Constipation",
"Smoker's Cough",
"Smoking Related Illnesses",
"Sore Throat",
"Spinning Sensation",
"Spontaneous Oto Acoustic Emission Tinnitus",
"Stomach",
"Stomach Flu",
"Stone Kidney",
"Stones Kidney",
"Stones kidney",
"Stress",
"Stress Disorders",
"Stress Related Disorders",
"Stress and Anxiety",
"Stridor",
"Stroke",
"Struvite stones",
"Subjective Tinnitus",
"Subungual warts",
"Sudden Cardiac Events",
"Systolic Heart Failure",
"TB",
"Tension",
"Tension Disorders",
"Tension Headache",
"Tensor Palatini Induced Tinnitus",
"Tensor Tympani Induced Tinnitus",
"Tertian malaria",
"Throat Irritation",
"Throat Pain",
"Throat and Neck Conditions",
"Tic Douloureux",
"Tic Douloureux Syndrome",
"Tinnitus",
"Tinnitus Clicking",
"Tinnitus Leudet",
"Tinnitus Leudet's",
"Tinnitus Leudets",
"Tinnitus Noise Induced",
"Tinnitus Objective",
"Tinnitus Pulsatile",
"Tinnitus Spontaneous Oto Acoustic Emission",
"Tinnitus Subjective",
"Tinnitus Tensor Palatini Induced",
"Tinnitus Tensor Tympani Induced",
"Tinnitus Vascular Origin",
"Tinnitus of Vascular Origin",
"Tooth Decay",
"Transitory Deafness",
"Transitory Deafnesses",
"Transitory Hearing Issues",
"Transitory Hearing Los",
"Transitory Hearing Losses",
"Traveler's Diarrhea",
"Tremor",
"Trigeminal Neuralgia",
"Tuberculosis",
"Types of Hearing Impairment",
"Ulcerative Colitis Chronic",
"Ulcertive colitis",
"Upper Respiratory Disorders",
"Upper Respiratory Infections",
"Uric acid stones",
"Urinary Bladder Diseases",
"Urinary Tract Infection UTI",
"Urinary Tract Infections UTI",
"Urinary lithiasis",
"Ursodeoxycholic acid UDCA ursodiol",
"Varicose",
"Varicose Veins",
"Vascular Diseases",
"Vascular Headache",
"Vascular Origin Tinnitus",
"Venous Diseases",
"Venous Insufficiency",
"Vernal Keratoconjunctivitides",
"Vernal Keratoconjunctivitis",
"Verruca",
"Verruca vulgaris",
"Verrucae planae juveniles",
"Vertigo",
"Vestibular Disorders",
"Viral Croup",
"Viral Gastroenteritis",
"Viral Hepatitis Infections",
"Viral Infections",
"Viral Meningitis",
"Viral Pneumonia",
"Viral Respiratory Diseases",
"Viral Vaccines",
"Visibly Distended Veins",
"Vocal Cord Disorders",
"Wakefulness",
"Warts",
"Watery Diarrhea",
"Wet Pleurisy",
"Zits",
"Zoonotic Diseases",
"blackheads",
"closed comedones",
"cysts",
"CDCA",
"gallstones chenodeoxycholic acids CDCA",
"laryngitis",
"nodules",
"open comedones",
"papules",
"pimples",
"pustules",
"whiteheads"
];
