const topicsSupported = [
  "Acne",
  "Diarrhea",
  "Meningitis",
  "Heart Problems",
  "Alzheimer's Disease",
  "Lupus",
  "Stress and Anxiety",
  "Senility",
  "Tic Douloureux",
  "Pancreatitis",
  "Migraine-2",
  "Cardiac Problems",
  "Bronchitis-2",
  "Headache",
  "Laryngitis",
  "Tuberculosis",
  "Epilepsy",
  "Pneumonia",
  "Ulcerative colitis",
  "Croup",
  "Cold sore",
  "Asthma-2",
  "Cough",
  "Cystitis-2",
  "Tooth Decay",
  "Malaria",
  "Gallstones",
  "Asthma",
  "Cough hydro",
  "Constipation",
  "Epilepsy-2",
  "Heart Failure",
  "Hepatitis E",
  "Lactose intolerance",
  "Sore Throat",
  "Stroke  copy",
  "Vertigo",
  "Croup-2",
  "Stroke",
  "Conjunctivitis",
  "Cystitis",
  "Multiple Sclerosis",
  "Bronchitis",
  "Fever reoccurrance",
  "Polio",
  "Meningitis-2",
  "Tinnitus",
  "Migraine",
  "Parkinson's Disease",
  "Sore Throat hydro",
  "Tuberculosis-2",
  "Headache-2",
  "Heart Attack",
  "Hearing loss",
  "Stroke-2",
  "Insomnia-2",
  "Hearing loss prevention",
  "Conjunctivitis prevention",
  "Fever",
  "Kidney Stones",
  "Insomnia",
  "Scabies",
  "Gastroenteritis",
  "Pleurisy",
  "Warts",
  "Pleurisy-2",
  "Varicose Veins",
  "Gallstones prevention",
  "Appendicitis",
  "Sore throat",
  "Bronchiectasis",
  "Psoriasis",
  "Sinusitis",
  "Bulimia",
];

export default topicsSupported;