const topicsSupported = [
  "Hyperthermia",
  "Acquired Immunodeficiency Syndrome",
  "Chickenpox",
  "Insomnia",
  "Anxiety",
  "Lupus",
  "Scabies",
  "Gout",
  "Bacteria",
  "Mumps",
  "Diabetes",
  "Lyme Disease",
  "Chronic",
  "Stroke",
  "Poliomyelitis",
  "Bursitis",
  "Alzheimer's",
  "Hepatitis",
  "Meningitis",
  "Asthma",
  "Sarcoma",
  "Cancer",
  "Tuberculosis",
  "Bulimia",
  "Asbestosis",
  "Bronchitis",
  "Leukemia",
  "Parkinson's Disease",
  "Dementia",
  "Tinnitus",
  "Malaria",
  "Plasmodium",
  "Aging",
  "Rheumatoid Arthritis",
  "Anaphylaxis",
  "Blood",
  "Mesothelioma",
  "Hodgkin Disease",
  "Measles",
  "Melanoma",
  "Arthritis",
  "Vertigo",
  "Pneumonia",
  "Obesity",
  "Hypertension",
  "Chemotherapy",
  "Ringworm",
  "Malnutrition",
  "Diarrhea",
];

export default topicsSupported;
