import allTagalogHealthKeywords from './health_keywords_tagalog';

const allKeywords = [ 
  ...allTagalogHealthKeywords,
    "Abdominal aortic aneurysm",
    "Acne",
    "Acute cholecystitis",
    "Acute lymphoblastic leukaemia",
    "Acute myeloid leukaemia",
    "Acute pancreatitis",
    "Addison's disease",
    "Alcohol misuse",
    "Alcohol poisoning",
    "Alcohol-related liver disease",
    "Allergic",
    "Allergic rhinitis",
    "Allergies",
    "Alzheimer's",
    "Alzheimer's disease",
    "Anal cancer",
    "Anaphylaxis",
    "Angioedema",
    "Ankylosing",
    "Ankylosing spondylitis",
    "Anorexia",
    "Anorexia nervosa",
    "Anxiety",
    "Anxiety disorders in children",
    "Appendicitis",
    "Arthritis",
    "Asbestosis",
    "Asthma",
    "Atopic eczema",
    "Attention deficit hyperactivity disorder",
    "Autistic",
    "Autistic spectrum disorder",
    "Bacteria",
    "Bacterial",
    "Bacterial vaginosis",
    "Benign",
    "Benign prostate enlargement",
    "Bile duct cancer",
    "Binge eating",
    "Bipolar",
    "Bipolar disorder",
    "Bladder",
    "Bladder cancer",
    "Blood",
    "Blood cancer",
    "Blood poisoning",
    "Bone",
    "Bone cancer",
    "Bowel",
    "Bowel cancer",
    "Bowel incontinence",
    "Bowel polyps",
    "Brain",
    "Brain stem death",
    "Brain tumours",
    "Breast",
    "Breast cancer",
    "Bronchiectasis",
    "Bronchitis",
    "Bulimia",
    "Bunion",
    "Bursitis",
    "Carcinoid",
    "Carcinoid syndrome and carcinoid tumours",
    "Catarrh",
    "Cellulitis",
    "Cervical",
    "Cervical cancer",
    "Chest infection",
    "Chest pain",
    "Chickenpox",
    "Chilblains",
    "Chronic",
    "Chronic fatigue syndrome",
    "Chronic kidney disease",
    "Chronic lymphocytic leukaemia",
    "Chronic myeloid leukaemia",
    "Chronic obstructive pulmonary disease",
    "Chronic pancreatitis",
    "Cirrhosis",
    "Clostridium",
    "Clostridium difficile",
    "Coeliac",
    "Coeliac disease",
    "Cold",
    "Cold sore",
    "Coma",
    "Common cold",
    "Common heart conditions",
    "Congenital",
    "Congenital heart disease",
    "Conjunctivitis",
    "Constipation",
    "Costochondritis",
    "Cough",
    "Crohn's",
    "Crohn's disease",
    "Croup",
    "Cystic",
    "Cystic fibrosis",
    "Cystitis",
    "Deafblindness",
    "Deep vein thrombosis",
    "Dehydration",
    "Dementia",
    "Dementia with Lewy bodies",
    "Dental",
    "Dental abscess",
    "Depression",
    "Dermatitis",
    "Dermatitis herpetiformis",
    "Diabetes",
    "Diabetic",
    "Diabetic retinopathy",
    "Diarrhoea",
    "Discoid",
    "Discoid eczema",
    "Diverticular",
    "Diverticular disease and diverticulitis",
    "Dizziness",
    "Down's syndrome",
    "Dry mouth",
    "Dysphagia",
    "Dystonia",
    "Earache",
    "Earwax",
    "Earwax build-up",
    "Ebola",
    "Ebola virus disease",
    "Ectopic",
    "Ectopic pregnancy",
    "Endometriosis",
    "Epilepsy",
    "Erectile",
    "Erectile dysfunction",
    "Escherichia",
    "Escherichia coli (E. coli) O157",
    "Ewing",
    "Ewing sarcoma",
    "Eye cancer",
    "Febrile",
    "Febrile seizures",
    "Fever",
    "Fever in children",
    "Fibroids",
    "Fibromyalgia",
    "Flatulence",
    "Flu",
    "Foetal",
    "Foetal alcohol syndrome",
    "Food poisoning",
    "Fungal",
    "Fungal nail infection",
    "Gallbladder",
    "Gallbladder cancer",
    "Gallstones",
    "Ganglion",
    "Ganglion cyst",
    "Gastroenteritis",
    "Gastro-oesophageal",
    "Gastro-oesophageal reflux disease",
    "Genital",
    "Genital herpes",
    "Genital warts",
    "Germ",
    "Germ cell tumours",
    "Glandular",
    "Glandular fever",
    "Gout",
    "Gum",
    "Gum disease",
    "Haemorrhoids",
    "Hairy",
    "Hairy cell leukaemia",
    "Hand",
    "Hand, foot and mouth disease",
    "Hay fever",
    "Head",
    "Head and neck cancer",
    "Head lice and nits",
    "Headaches",
    "Hearing",
    "Hearing loss",
    "Heart",
    "Heart failure",
    "Hepatitis",
    "Hepatitis A",
    "Hepatitis B",
    "Hepatitis C",
    "Hiatus",
    "Hiatus hernia",
    "High cholesterol",
    "HIV",
    "Hodgkin",
    "Hodgkin lymphoma",
    "Huntington's",
    "Huntington's disease",
    "Hyperglycaemia",
    "Hyperhidrosis",
    "Hypoglycaemia",
    "Idiopathic",
    "Idiopathic pulmonary fibrosis",
    "Impetigo",
    "Indigestion",
    "Ingrown",
    "Ingrown toenail",
    "Inherited",
    "Inherited heart conditions",
    "Insomnia",
    "Iron deficiency anaemia",
    "Irritable",
    "Irritable bowel syndrome",
    "Irritable hip",
    "Itching",
    "Itchy",
    "Itchy bottom",
    "Kaposi's",
    "Kaposi's sarcoma",
    "Kidney",
    "Kidney cancer",
    "Kidney infection",
    "Kidney stones",
    "Labyrinthitis",
    "Lactose",
    "Lactose intolerance",
    "Langerhans",
    "Langerhans cell histiocytosis",
    "Laryngeal",
    "Laryngeal (larynx) cancer",
    "Laryngitis",
    "Leg",
    "Leg cramps",
    "Lichen",
    "Lichen planus",
    "Liver",
    "Liver cancer",
    "Liver disease",
    "Liver tumours",
    "Loss",
    "Loss of libido",
    "Lung",
    "Lung cancer",
    "Lupus",
    "Lyme",
    "Lyme disease",
    "Lymphoedema",
    "Malaria",
    "Malignant",
    "Malignant brain tumour",
    "Malnutrition",
    "Measles",
    "Meningitis",
    "Menopause",
    "Mesothelioma",
    "Middle ear infection",
    "Migraine",
    "Miscarriage",
    "Motor neurone disease",
    "Mouth",
    "Mouth cancer",
    "Mouth ulcer",
    "Multiple myeloma",
    "Multiple sclerosis",
    "Mumps",
    "Meniere's",
    "Nasal",
    "Nasal and sinus cancer",
    "Nasopharyngeal",
    "Nasopharyngeal cancer",
    "Neuroblastoma",
    "Neuroendocrine",
    "Neuroendocrine tumours",
    "New or worsening back pain",
    "Non-alcoholic",
    "Non-alcoholic fatty liver disease",
    "Non-Hodgkin",
    "Non-Hodgkin lymphoma",
    "Norovirus",
    "Nosebleed",
    "Obesity",
    "Obsessive",
    "Obsessive compulsive disorder",
    "Obstructive",
    "Obstructive sleep apnoea",
    "Oesophageal",
    "Oesophageal cancer",
    "Oral",
    "Oral thrush in adults",
    "Osteoarthritis",
    "Osteoporosis",
    "Osteosarcoma",
    "Otitis",
    "Otitis externa",
    "Ovarian",
    "Ovarian cancer",
    "Ovarian cyst",
    "Overactive",
    "Overactive thyroid",
    "Paget's",
    "Paget's disease of the nipple",
    "Pancreatic",
    "Pancreatitis",
    "Pancreatic cancer",
    "Panic",
    "Panic disorder",
    "Parkinson's",
    "Parkinson's disease",
    "Pelvic",
    "Pelvic organ prolapse",
    "Penile",
    "Penile cancer",
    "Peripheral",
    "Peripheral neuropathy",
    "Personality",
    "Personality disorder",
    "Pleurisy",
    "Pneumonia",
    "Polymyalgia",
    "Polymyalgia rheumatica",
    "Post-traumatic",
    "Post-traumatic stress disorder",
    "Postnatal",
    "Postnatal depression",
    "Pregnancy and baby",
    "Pressure",
    "Pressure ulcers",
    "Prostate",
    "Prostate cancer",
    "Psoriasis",
    "Psoriatic",
    "Psoriatic arthritis",
    "Psychosis",
    "Rare",
    "Rare tumours",
    "Raynaud's",
    "Raynaud's phenomenon",
    "Reactive",
    "Reactive arthritis",
    "Restless",
    "Restless legs syndrome",
    "Retinoblastoma",
    "Rhabdomyosarcoma",
    "Rheumatoid",
    "Rheumatoid arthritis",
    "Ringworm",
    "Ringworm and other fungal infections",
    "Rosacea",
    "Scabies",
    "Scarlet",
    "Scarlet fever",
    "Schizophrenia",
    "Scoliosis",
    "Septic",
    "Septic shock",
    "Sexually",
    "Sexually transmitted infections",
    "Shingles",
    "Shortness",
    "Shortness of breath",
    "Sickle",
    "Sickle cell disease",
    "Sinusitis",
    "Sjogren's",
    "Sjogren's syndrome",
    "Skin",
    "Skin cancer",
    "Slapped",
    "Slapped cheek syndrome",
    "Soft",
    "Soft tissue sarcomas",
    "Sore",
    "Sore throat",
    "Spleen",
    "Spleen problems and spleen removal",
    "Stillbirth",
    "Stomach",
    "Stomach ache and abdominal pain",
    "Stomach cancer",
    "Stomach ulcer",
    "Stress",
    "Stress, anxiety and low mood",
    "Stroke",
    "Sudden",
    "Sudden infant death syndrome",
    "Suicide",
    "Sunburn",
    "Swollen",
    "Swollen glands",
    "Testicular",
    "Testicular cancer",
    "Testicular lumps and swellings",
    "Thirst",
    "Threadworms",
    "Thrush",
    "Thrush in men",
    "Thyroid",
    "Thyroid cancer",
    "Tinnitus",
    "Tonsillitis",
    "Tooth",
    "Tooth decay",
    "Toothache",
    "Transient",
    "Transient ischaemic attack",
    "Trigeminal",
    "Trigeminal neuralgia",
    "Tuberculosis",
    "Type 1 diabetes",
    "Type 2 diabetes",
    "Ulcerative",
    "Ulcerative colitis",
    "Underactive",
    "Underactive thyroid",
    "Urinary",
    "Urinary incontinence",
    "Urinary tract infection",
    "Urinary tract infection (UTI) in children",
    "Urticaria",
    "Vaginal",
    "Vaginal cancer",
    "Vaginal thrush",
    "Varicose",
    "Varicose eczema",
    "Varicose veins",
    "Venous",
    "Venous leg ulcer",
    "Vertigo",
    "Vitamin",
    "Vitamin B12 or folate deficiency anaemia",
    "Vomiting",
    "Vomiting in adults",
    "Vulval",
    "Vulval cancer",
    "Warts",
    "Warts and verrucas",
    "Whooping",
    "Whooping cough",
    "Wilms'",
    "Wilms' tumour",
    "Womb",
    "Womb (uterus) cancer",
    "Yellow",
    "Yellow fever",
    "Coronavirus",
    "COVID-19",
    "Monkeypox",
    "Mpox",
    "Long COVID",
    "Polio",
    "Respiratory syncytial virus (RSV)",
    "Mpox (Monkeypox)",
    "Hepatitis E",
    "Hepatitis D",
    "Hepatitis G",
    "Hepatitis F"
  ];
  
  export {
    allKeywords
  }